language: node_js
node_js:
- '6'
- '8'
script: npm run test-local
before_install:
- openssl aes-256-cbc -K $encrypted_260f5982fb87_key -iv $encrypted_260f5982fb87_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 59.110.233.80\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

after_success:
- tar -jcf Blog.tar.bz2 * --exclude=node_modules
- scp Blog.tar.bz2 root@59.110.233.80:/home/Blog
- ssh root@59.110.233.80 'cd /home/Blog && tar -jxf Blog.tar.bz2'
- ssh root@59.110.233.80 'cd /home/Blog  && npm run start'
