language: node_js
node_js:
- '8'
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_260f5982fb87_key -iv $encrypted_260f5982fb87_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 59.110.233.80\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mysql -u root -e 'CREATE DATABASE Koa;'
- mysql -u root Koa < test/travis.sql
install:
- npm i npminstall && npminstall
script:
- npm run travis 
after_success:
- bash <(curl -s https://codecov.io/bash)
- tar -jcf Blog.tar.bz2 * --exclude=node_modules --exclude=config.js --exclude=app/md
- scp Blog.tar.bz2 root@59.110.233.80:/home/Blog
- ssh root@59.110.233.80 'cd /home/Blog && tar -jxf Blog.tar.bz2'
- ssh root@59.110.233.80 'cd /home/Blog && npm stop && npm start && webpack'
