language: node_js
node_js:
- '6'
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_260f5982fb87_key -iv $encrypted_260f5982fb87_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 59.110.233.80\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm i npminstall && npminstall
script:
- TESTS=test/index.test.js npm test
after_success:
- tar -jcf Blog.tar.bz2 * --exclude=node_modules
- scp Blog.tar.bz2 root@59.110.233.80:/home/Blog
- ssh root@59.110.233.80 'cd /home/Blog && tar -jxf Blog.tar.bz2'
- ssh root@59.110.233.80 'cd /home/Blog && npm run stop && npm run start'
env:
  global:
    - secure=cCgRY2wpVQnpmsuYcF3dBn5OfvYHH6pIR6ku52C8wgBGYSqCWiChQ0xwSTR8daRbVG+ZYK+bMHgCZ2rMd5nw1jA28bStOEfebLqPyFCxaK3QVKnY9Gei9ZjcdFnMoK0k7EXsD2qwzCu9pdMqTzBl1hvQxmzizggwAygnUxy6qm2t3wVuMh/miNLsmPoQFjPdV3RTAUBgKxbd8mz4G1KarppRMj/h2DlCH7AD7qPe3kbYbPKnhTVVdCUjOCRMa/1z21k2QP74WzO9OqtJ2blsDqeH+Y0gGmUytXXAn3VPGwCuGLfygltFvEUCrlN919w+SHkMMywaV5scWtk27CzkHrRXjb0osTEdVV1q+PCVRFy/FTnNUd3/POqADbiQ2Fdu91gtp6ZuJllCeB15NVI5oSNQZfrC5Hx1pdOp6/3DDtVDh4OHlfwD94JhcosdkJcFX5/V1O/lF0lRUu5uF9RLJDSdZykb2Cwn2BM2Azhu4ZaYJf54i2O/3BNfW+jNPkmf3yj5F3tAzi6NP3ImgZPo+5zo+i0zO12ugjDC6ELX5IPm+u62g2qdAKfR7Vnlv1tJ1U9lJ2wQpS5UFuQtkftdSxn1P0MKVkBARWGhhw2Q4VSYYUUOB74OrSNumOOLrTxCHq3agrVOB2hC4QCcuy6pgiZhHt+tTbeNTqz+hf/JLHY=
